language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - flake8 .
  - python -m pytest tests/test_*.py
  - python setup.py sdist bdist_wheel
  - pip install --process-dependency-links dist/coverage_crawler-1.0.0.tar.gz
